import 'package:easy_localization/easy_localization.dart';

class StringValue {
  static String welcome = "welcome".tr();
  static String fullName = "full_name".tr();
  static String mobileNo = "mobile_number".tr();
  static String email = "email".tr();
  static String address = "address".tr();
  static String state = "state".tr();
  static String gender = "gender".tr();
  static String dob = "date_of_birth".tr();
  static String about = "about_us".tr();
  static String date = "date".tr();
  static String smsEnable = "sms_notifications".tr();
  static String emailEnable = "email_notifications".tr();
  static String english = "english".tr();
  static String editProfile = "edit_profile".tr();
  static String dartMode = "dark_mode".tr();
  static String password = "password".tr();
  static String privacy = "privacy".tr();
  static String support = "support".tr();
  static String setting = "settings".tr();
  static String programName = "programme_name".tr();
  static String time = "time".tr();
  static String organize = "organizer".tr();
  static String aboutThisProgram = "about_the_programme".tr();
  static String artistName = "artist_name".tr();
  static String entry = "entry".tr();
  static String artCategory = "art_category".tr();
  static String artistInfo = "artist_introduction".tr();
  static String gallery = "gallery".tr();
  static String pogramCategory = "program_category".tr();
  static String liveProgram = "live_program".tr();
  static String todayProgram = "today_program".tr();
  static String upcomingProgram = "upcoming_program".tr();
  static String archivedProgram = "archived_program".tr();
  static String artsCategory = "arts_categories".tr();
  static String logOut = "log_out".tr();
  static String logIn = "login".tr();
  static String haveAccount = "have_account".tr();
  static String signUp = "sign_up".tr();
  static String enterMobileNo = "enter_mobile_no".tr();
  static String enterOtp = "enter_otp".tr();
  static String registrationForProgram = "registration_for_program".tr();
  static String registrationForArtist = "registration_for_artist".tr();
  static String allCategory = "all_category".tr();
  static String updateSave = "save_update".tr();
  static String updateAccount = "update_account".tr();
  static String register = "registration".tr();
  static String cancel = "cancel".tr();
  static String close = "close".tr();
  static String copy = "copy".tr();
  static String contactWithUs = "contact_wit_us".tr();
  static String emailCopyDone = "email_copy_done".tr();
  static String loginForView = "login_for_view".tr();
  static String loginForProgram = "login_for_view_program".tr();
  //--------------- url no need to tranlate -------------------------//
  static const String privicyUrl =
      "https://jusmarktech.in/Mp_culture_app_privacy_policy.html";
  static const String artistRegisterUrl =
      "https://jusmarktech.in/mpculturedept/artistregistration.php";
  static const String contactEmail = "proculturemp@gmail.com";

  //----------.....----- Update function ------------.....-------------//

  static void updateValues() {
    welcome = "welcome".tr();
    fullName = "full_name".tr();
    mobileNo = "mobile_number".tr();
    email = "email".tr();
    address = "address".tr();
    state = "state".tr();
    gender = "gender".tr();
    dob = "date_of_birth".tr();
    about = "about_us".tr();
    date = "date".tr();
    smsEnable = "sms_notifications".tr();
    emailEnable = "email_notifications".tr();
    english = "english".tr();
    editProfile = "edit_profile".tr();
    dartMode = "dark_mode".tr();
    password = "password".tr();
    privacy = "privacy".tr();
    support = "support".tr();
    setting = "settings".tr();
    programName = "programme_name".tr();
    time = "time".tr();
    organize = "organizer".tr();
    aboutThisProgram = "about_the_programme".tr();
    artistName = "artist_name".tr();
    entry = "entry".tr();
    artCategory = "art_category".tr();
    artistInfo = "artist_introduction".tr();
    gallery = "gallery".tr();
    pogramCategory = "program_category".tr();
    liveProgram = "live_program".tr();
    todayProgram = "today_program".tr();
    upcomingProgram = "upcoming_program".tr();
    archivedProgram = "archived_program".tr();
    artsCategory = "arts_categories".tr();
    logOut = "log_out".tr();
    logIn = "login".tr();
    haveAccount = "have_account".tr();
    signUp = "sign_up".tr();
    enterMobileNo = "enter_mobile_no".tr();
    enterOtp = "enter_otp".tr();
    registrationForProgram = "registration_for_program".tr();
    registrationForArtist = "registration_for_artist".tr();
    allCategory = "all_category".tr();
    updateSave = "save_update".tr();
    updateAccount = "update_account".tr();
    register = "registration".tr();
    close = "close".tr();
    copy = "copy".tr();
    contactWithUs = "contact_wit_us".tr();
    emailCopyDone = "email_copy_done".tr();
    loginForView = "login_for_view".tr();
    loginForProgram = "login_for_view_program".tr();
  }
}
